// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package repository

import (
	"context"
)

const findAllProducts = `-- name: FindAllProducts :many
SELECT
    id, name
FROM
    products
`

func (q *Queries) FindAllProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.Query(ctx, findAllProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
